resor_core:
    resource: "@ResorCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

resor_api:
    type: rest
    resource: Resor\Bundle\CoreBundle\Controller\ApiController
    prefix: /api/