<?php

namespace Resor\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampingRepository extends EntityRepository
{
    public function findLikeName($name)
    {
        return $this->createQueryBuilder('c')
            ->where('c.name LIKE :name')
            ->setParameter('name', '%' .  $name . '%')
            ->getQuery()
            ->getResult();
    }
}
