<?php

namespace Resor\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampingRepository extends EntityRepository
{
}
