<?php

namespace Resor\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    public function findAround($lat, $lng)
    {
        $parameters = array(
            'latMin' => floor($lat),
            'latMax' => ceil($lat),
            'lngMin' => floor($lng),
            'lngMax' => ceil($lng)
        );
        return $this->createQueryBuilder('o')
            ->join('o.camping', 'c')
            ->where('c.isActive = 1')
            ->andWhere('c.lat > :latMin')
            ->andWhere('c.lat < :latMax')
            ->andWhere('c.lng > :lngMin')
            ->andWhere('c.lng < :lngMax')
            ->setParameters($parameters)
            ->getQuery()
            ->getResult();
    }

    public function findForCampingId($camping_id)
    {
        return $this->createQueryBuilder('o')
            ->join('o.camping', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $camping_id)
            ->getQuery()
            ->getResult();
    }

    public function canBook ($offer, $wantedBook)
    {
        // TODO IMPLEMENT METHOD
        return true;
    }
}
